# Generated by Django 4.0.6 on 2022-08-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_type_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField()),
                ('FIELDNAME', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'managed': True, 'verbose_name': 'Phone', 'verbose_name_plural': 'Phone'},
        ),
        migrations.AlterModelTable(
            name='phone',
            table='Phone',
        ),
    ]
