# Generated by Django 4.0.6 on 2022-08-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact_alter_phone_options_alter_phone_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='FIELDNAME',
            new_name='sent',
        ),
    ]
