# Generated by Django 4.0.6 on 2022-08-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_fieldname_contact_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': True, 'verbose_name': 'Contact', 'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
