# Generated by Django 4.0.6 on 2022-08-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contact_options_alter_contact_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
